### ISSUE TITLE
we discarded Geoserver, what are the alternatives?

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/docker-geoserver#2]
After working with it, we concluded that GeoServer is not suitable for our project. We will use S3 instead to storage the map functionalities. Is this correct?

**Comment by Maartenvm** [comment]
Yes, largely. Depends on what additional requirements come along. We don't need it for the region mapping, which is what we initially thought it would be used for.

**Comment by ctwhome** [comment]
That sounds good, let's close the issue and move it to the done column.
